# Server Port
server.port=3000

# Bind to all network interfaces (important for real devices)
server.address=0.0.0.0

# RapidAPI Key
rapidapi.key=257db6bbbamsh6d2fcc1e5a54ee6p17584bjsn2428a7d6e7ad
